"""Criar tabelas usina e inversor

Revision ID: 60bf17c2cb41
Revises: 
Create Date: 2025-05-11 18:11:20.565955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bf17c2cb41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inversor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('usina_id', sa.Integer(), nullable=False),
    sa.Column('potencia_maxima', sa.Float(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usina_id'], ['usina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inversor_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('potencia_ativa_watt', sa.Float(), nullable=False),
    sa.Column('temperatura_celsius', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inversor_id'], ['inversor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leitura')
    op.drop_table('inversor')
    op.drop_table('usina')
    # ### end Alembic commands ###
